# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "My Blog"
description: > # this means to ignore newlines until "email:"
   Ruby developer's way

email: igorek1mamutkin@gmail.com
#blog logo
logo: "/assets/images/blog.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ihar Mamutkin'
author: 'Ihar Mamutkin'
author_image: "/assets/images/my_foto.jpeg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
instagram_handle: '@igorek_mamutkin'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://www.instagram.com/igorek_mamutkin/
    desc: Follow me on instagram

  - icon:	github
    url:	https://github.com/igormamutkin
    desc:	Fork me on github

